window.PED_REL = [
  {"cid":"otonashietsuko","pure":true},
  {"cid":"kiryuinaoi","pure":true},
  {"cid":"anshinzawasasami","pure":true},
  {"cid":"kashimotoriko","pure":true},
  {"cid":"satakemei","pure":true},
  {"cid":"tsurugiryoka","pure":true},
  {"cid":"hoshinakiyoko","pure":true},
  {"cid":"akasakamisato","pure":true},
  {"cid":"hosoejunko","pure":true},
  {"cid":"spica_trainer","pure":true}
,
  {"cid": "bochuzoku", "real": "モンジュー", "zh": "望族", "av": "/uma_official/bochuzoku.png", "up": [["real_sadlers_wells", "real_floripedes"], ["real_northern_dancer", "real_fairy_bridge", "real_top_ville", "real_toute_cy"], ["real_nearctic", "real_natalma", "real_bold_reason", "real_special", "real_high_top", "real_sega_ville", "real_tennyson", "real_adele_toumignon"]], "children": [], "grandchildren": []},
  {"cid": "real_sadlers_wells", "real": "Sadler's Wells", "zh": "", "av": "", "up": [[], [], []], "children": [], "grandchildren": []},
  {"cid": "real_floripedes", "real": "Floripedes", "zh": "", "av": "", "up": [[], [], []], "children": [], "grandchildren": []},
  {"cid": "real_northern_dancer", "real": "Northern Dancer", "zh": "", "av": "", "up": [[], [], []], "children": [], "grandchildren": []},
  {"cid": "real_fairy_bridge", "real": "Fairy Bridge", "zh": "", "av": "", "up": [[], [], []], "children": [], "grandchildren": []},
  {"cid": "real_top_ville", "real": "Top Ville", "zh": "", "av": "", "up": [[], [], []], "children": [], "grandchildren": []},
  {"cid": "real_toute_cy", "real": "Toute Cy", "zh": "", "av": "", "up": [[], [], []], "children": [], "grandchildren": []},
  {"cid": "real_nearctic", "real": "Nearctic", "zh": "", "av": "", "up": [[], [], []], "children": [], "grandchildren": []},
  {"cid": "real_natalma", "real": "Natalma", "zh": "", "av": "", "up": [[], [], []], "children": [], "grandchildren": []},
  {"cid": "real_bold_reason", "real": "Bold Reason", "zh": "", "av": "", "up": [[], [], []], "children": [], "grandchildren": []},
  {"cid": "real_special", "real": "Special", "zh": "", "av": "", "up": [[], [], []], "children": [], "grandchildren": []},
  {"cid": "real_high_top", "real": "High Top", "zh": "", "av": "", "up": [[], [], []], "children": [], "grandchildren": []},
  {"cid": "real_sega_ville", "real": "Sega Ville", "zh": "", "av": "", "up": [[], [], []], "children": [], "grandchildren": []},
  {"cid": "real_tennyson", "real": "Tennyson", "zh": "", "av": "", "up": [[], [], []], "children": [], "grandchildren": []},
  {"cid": "real_adele_toumignon", "real": "Adele Toumignon", "zh": "", "av": "", "up": [[], [], []], "children": [], "grandchildren": []}];
