# -*- coding: utf-8 -*-
"""Fetch voice actor photos from Moegirl (萌娘百科) pageimages.
Downloads to G:/学习/AI/uma_va/ and writes va_photos_data.js manifest."""
import urllib.request, urllib.parse, json, re, os, time, io, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

ROOT = r'G:\学习\AI'
OUT_DIR = os.path.join(ROOT, 'uma_va')
TMP = r'C:\Users\51673\AppData\Local\Temp\opencode'
STATE = os.path.join(TMP, 'va_photo_state2.json')
UA = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}

os.makedirs(OUT_DIR, exist_ok=True)

def get_json(url):
    return json.loads(urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=25).read().decode('utf-8'))

def get_bytes(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=40).read()

def sanitize(name):
    s = re.sub(r'[^\w\u4e00-\u9fff\u3040-\u30ff\u3005\u3006\u30fc]+', '_', str(name))
    return s.strip('_') or 'va'

def api_quote(t):
    return urllib.parse.quote(t.replace(' ', '_'), safe='')

def find_page(name):
    q = urllib.parse.quote(name)
    try:
        r = get_json('https://zh.moegirl.org.cn/api.php?action=opensearch&search=%s&limit=5&format=json' % q)
        titles = r[1] if len(r) > 1 else []
    except Exception:
        return None
    if not titles:
        return None
    for t in titles:
        if name in t or t == name:
            return t
    return titles[0]

def get_photo(title):
    try:
        r = get_json('https://zh.moegirl.org.cn/api.php?action=query&titles=%s&prop=pageimages&piprop=thumbnail&pithumbsize=560&format=json' % api_quote(title))
    except Exception:
        return None
    pages = r.get('query', {}).get('pages', {})
    for _, pg in pages.items():
        th = (pg.get('thumbnail') or {}).get('source')
        if th:
            return th
    return None

def load_state():
    if os.path.exists(STATE):
        return json.load(open(STATE, encoding='utf-8'))
    return {}

def main():
    src = open(os.path.join(ROOT, 'character_index_data.js'), encoding='utf-8').read()
    m = re.search(r'window\.CHAR_INDEX\s*=\s*(\[.*?\]);?\s*$', src, re.S)
    chars = json.loads(m.group(1))
    order = []
    groups = {}
    for c in chars:
        key = c.get('cv_zh') or c.get('cv')
        if not key or key in groups:
            continue
        groups[key] = c
        order.append(key)

    st = load_state()
    manifest = {}
    done = fail = 0
    t0 = time.time()
    for i, key in enumerate(order):
        if st.get(key, {}).get('ok'):
            manifest[key] = st[key]['entry']
            done += 1
            continue
        c = groups[key]
        names = []
        for nm in [c.get('cv_zh'), c.get('cv')]:
            if nm and nm not in names:
                names.append(nm)
        entry = None
        for nm in names:
            title = find_page(nm)
            time.sleep(0.15)
            if not title:
                continue
            ph = get_photo(title)
            time.sleep(0.15)
            if not ph:
                continue
            fn = 'va_%s.jpg' % sanitize(key)
            try:
                data = get_bytes(ph)
                if data[:3] in (b'\xff\xd8\xff', b'\x89PN') and len(data) > 5000:
                    open(os.path.join(OUT_DIR, fn), 'wb').write(data)
                    entry = {
                        'img': '/uma_va/' + fn,
                        'page': 'https://zh.moegirl.org.cn/' + api_quote(title),
                        'title': title,
                    }
                    break
            except Exception as ex:
                print('DL FAIL', key, str(ex)[:80])
        st[key] = {'ok': bool(entry), 'entry': entry}
        if entry:
            manifest[key] = entry
            done += 1
        else:
            fail += 1
        if i % 10 == 0 or i == len(order) - 1:
            json.dump(st, open(STATE, 'w', encoding='utf-8'), ensure_ascii=False)
            el = round(time.time() - t0)
            print('[%d/%d] ok=%d miss=%d %ds cur=%s' % (i + 1, len(order), done, fail, el, key), flush=True)

    json.dump(st, open(STATE, 'w', encoding='utf-8'), ensure_ascii=False)
    out = ['// auto-generated by fetch_va_photos_moegirl.py']
    out.append('window.VA_PHOTOS = %s;' % json.dumps(manifest, ensure_ascii=False))
    open(os.path.join(ROOT, 'va_photos_data.js'), 'w', encoding='utf-8').write('\n'.join(out))
    missing = [k for k in order if k not in manifest]
    print('DONE total=%d with_photo=%d missing=%d' % (len(order), len(manifest), len(missing)), flush=True)
    if missing:
        print('MISSING:', ' | '.join(missing))

if __name__ == '__main__':
    main()
