# -*- coding: utf-8 -*-
"""Fetch VA birthdays from moegirl pages, merge into va_photos_data.js."""
import urllib.request, urllib.parse, json, re, os, time, io, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

ROOT = r'G:\学习\AI'
TMP = r'C:\Users\51673\AppData\Local\Temp\opencode'
STATE = os.path.join(TMP, 'va_photo_state2.json')
UA = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
DATE_RE = re.compile(r'(19|20)\d{2}年\d{1,2}月\d{1,2}日')

def get_html(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30).read().decode('utf-8', 'replace')

def extract_birth(html):
    rows = re.findall(r'<tr[^>]*>((?:(?!</tr>).)*?(?:出生|生年|生日|诞辰)(?:(?!</tr>).)*?)</tr>', html, re.S)
    for row in rows:
        txt = re.sub(r'<[^>]+>', ' ', row)
        txt = re.sub(r'\s+', ' ', txt).strip()
        if '索引' in txt or '查' in txt[:3]:
            continue
        m = DATE_RE.search(txt)
        if m:
            return m.group(0)
    return ''

def main():
    st = json.load(open(STATE, encoding='utf-8'))
    keys = [k for k, v in st.items()]
    got = 0
    for i, key in enumerate(keys):
        v = st[key]
        already = (v.get('entry') or {}).get('birth') or v.get('birth_try')
        if already:
            got += 1
            continue
        title = (v.get('entry') or {}).get('title') or key
        q = urllib.parse.quote(str(title).replace(' ', '_'), safe='')
        birth = ''
        try:
            html = get_html('https://zh.moegirl.org.cn/' + q)
            birth = extract_birth(html)
        except Exception:
            pass
        if v.get('ok'):
            v['entry']['birth'] = birth
        else:
            v['birth_try'] = birth
        if birth:
            got += 1
        if i % 20 == 0:
            print('[%d/%d] got=%d cur=%s -> %s' % (i + 1, len(keys), got, key, birth), flush=True)
            json.dump(st, open(STATE, 'w', encoding='utf-8'), ensure_ascii=False)
        time.sleep(0.25)
    json.dump(st, open(STATE, 'w', encoding='utf-8'), ensure_ascii=False)

    manifest = {}
    for k, v in st.items():
        if v.get('ok'):
            e = dict(v['entry'])
            if not e.get('birth'):
                e['birth'] = v.get('birth_try', '')
            manifest[k] = e
    out = ['// auto-generated by fetch_va_photos_moegirl.py']
    out.append('window.VA_PHOTOS = %s;' % json.dumps(manifest, ensure_ascii=False))
    open(os.path.join(ROOT, 'va_photos_data.js'), 'w', encoding='utf-8').write('\n'.join(out))
    nobirth = [k for k, v in manifest.items() if not v.get('birth')]
    print('DONE entries=%d with_birth=%d no_birth=%d' % (len(manifest), len(manifest) - len(nobirth), len(nobirth)))
    if nobirth:
        print('NO BIRTH:', ' | '.join(nobirth))

if __name__ == '__main__':
    main()
