# -*- coding: utf-8 -*-
"""Fetch 7 VA avatars: unavatar.io proxied through wsrv.nl."""
import urllib.request, urllib.parse, json, re, os, io, sys, time
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
from PIL import Image

ROOT = r'G:\学习\AI'
OUT_DIR = os.path.join(ROOT, 'uma_va')
MANIFEST = os.path.join(ROOT, 'va_photos_data.js')
STATE = r'C:\Users\51673\AppData\Local\Temp\opencode\va_photo_state2.json'
UA = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}

TARGETS = {
    '秋山实咲':   ('misaki_aoni',    '8月2日'),
    '望月裕美子': ('mochi_yumi25',   '5月25日'),
    '野木奏':     ('kana_nogi0911',  '9月11日'),
    '真名濑日和': ('Hiyori_Manase',  '2月27日'),
    '小田杏树':   ('Anju_oda0130',   '1月30日'),
    '折原日菜':   ('Hina_orihara_',  '5月8日'),
    '井料爱良':   ('Aira_Iryo',      '9月19日'),
}

def get(u):
    return urllib.request.urlopen(urllib.request.Request(u, headers=UA), timeout=60).read()

def sanitize(name):
    s = re.sub(r'[^\w\u4e00-\u9fff\u3040-\u30ff\u3005\u3006\u30fc]+', '_', str(name))
    return s.strip('_') or 'va'

src = open(MANIFEST, encoding='utf-8').read()
manifest = json.loads(re.search(r'window\.VA_PHOTOS\s*=\s*(\{.*\});?\s*$', src, re.S).group(1))
st = json.load(open(STATE, encoding='utf-8'))

ok_all = True
for key, (handle, birth) in TARGETS.items():
    fn = 'va_%s.jpg' % sanitize(key)
    final = os.path.join(OUT_DIR, fn)
    inner = urllib.parse.quote('https://unavatar.io/twitter/' + handle + '?fallback=false', safe='')
    got = False
    for attempt in range(3):
        try:
            data = get('https://wsrv.nl/?url=' + inner)
            tmp = final + '.tmp'
            open(tmp, 'wb').write(data)
            img = Image.open(tmp); img.load()
            w, h = img.size
            if w < 80 or h < 80:
                os.remove(tmp); raise ValueError('too small %dx%d' % (w, h))
            if img.mode != 'RGB':
                bg = Image.new('RGB', img.size, (255, 255, 255))
                bg.paste(img.convert('RGBA'), mask=img.convert('RGBA').split()[-1])
                img = bg
            if max(img.size) > 300:
                img.thumbnail((300, 300), Image.LANCZOS)
            img.save(final, 'JPEG', quality=75, optimize=True)
            os.remove(tmp)
            print('%s <- @%s OK (%dx%d -> %dKB)' % (key, handle, w, h, os.path.getsize(final)//1024))
            entry = {'img': '/uma_va/' + fn, 'page': 'https://x.com/' + handle, 'title': '@' + handle, 'birth': birth}
            manifest[key] = entry
            st[key] = {'ok': True, 'entry': entry}
            got = True
            break
        except Exception as ex:
            msg = str(ex)
            if '404' in msg:
                print('%s <- @%s : upstream 404 (no avatar / bad handle), skip retries' % (key, handle))
                break
            print('%s <- @%s attempt%d FAIL: %s' % (key, handle, attempt+1, msg[:90]))
            time.sleep(2)
    if not got:
        ok_all = False

json.dump(st, open(STATE, 'w', encoding='utf-8'), ensure_ascii=False)
out = ['// auto-generated by fetch_va_photos_moegirl.py']
out.append('window.VA_PHOTOS = %s;' % json.dumps(manifest, ensure_ascii=False))
open(MANIFEST, 'w', encoding='utf-8').write('\n'.join(out))

missing_files = [k for k, v in manifest.items() if not os.path.exists(os.path.join(ROOT, v['img'].lstrip('/')))]
print('DONE manifest=%d broken_paths=%s' % (len(manifest), missing_files or 'none'))
print('ALL7 OK' if ok_all else 'SOME FAILED')
