# -*- coding: utf-8 -*-
"""Round 2: fetch remaining 4 VA photos (+redo Orihara Hina headshot)."""
import urllib.request, re, json, os, io, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
from PIL import Image

ROOT = r'G:\学习\AI'
OUT_DIR = os.path.join(ROOT, 'uma_va')
MANIFEST = os.path.join(ROOT, 'va_photos_data.js')
STATE = r'C:\Users\51673\AppData\Local\Temp\opencode\va_photo_state2.json'
UA = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}

def fetch(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=40).read()

def get_html(url):
    return fetch(url).decode('utf-8', 'replace')

def og_image(url):
    h = get_html(url)
    for m in re.findall(r'<meta[^>]+>', h, re.I):
        if 'og:image' in m and 'content=' in m.lower():
            c = re.search(r'content=["\']([^"\']+)["\']', m, re.I)
            if c:
                u = c.group(1)
                if u.startswith('//'): u = 'https:' + u
                return urllib.parse.urljoin(url, u)
    return None

import urllib.parse

def save_img(data, final):
    tmp = final + '.tmp'
    open(tmp, 'wb').write(data)
    img = Image.open(tmp); img.load()
    w, h = img.size
    if w < 100 or h < 100 or w / h > 2.2:
        os.remove(tmp); raise ValueError('bad shape %dx%d' % (w, h))
    if img.mode != 'RGB':
        bg = Image.new('RGB', img.size, (255, 255, 255))
        if img.mode in ('RGBA', 'LA', 'P'):
            bg.paste(img.convert('RGBA'), mask=img.convert('RGBA').split()[-1])
        else:
            bg.paste(img)
        img = bg
    if h > w * 2.4:
        img = img.crop((0, 0, w, int(w * 1.5)))
    w2, h2 = img.size
    if max(w2, h2) > 300:
        if w2 >= h2:
            img = img.resize((300, int(h2 * 300 / w2)), Image.LANCZOS)
        else:
            img = img.resize((int(w2 * 300 / h2), 300), Image.LANCZOS)
    img.save(final, 'JPEG', quality=75, optimize=True)
    os.remove(tmp)

def sanitize(name):
    s = re.sub(r'[^\w\u4e00-\u9fff\u3040-\u30ff\u3005\u3006\u30fc]+', '_', str(name))
    return s.strip('_') or 'va'

src = open(MANIFEST, encoding='utf-8').read()
manifest = json.loads(re.search(r'window\.VA_PHOTOS\s*=\s*(\{.*\});?\s*$', src, re.S).group(1))
st = json.load(open(STATE, encoding='utf-8'))

JOBS = [
    # key, image urls to try, page url for credit link, handle, birth, overwrite?
    ('秋山实咲',   ['https://www.aoni.co.jp/search/items/akiyama-misaki.jpg'], None, 'misaki_aoni', '8月2日'),
    ('野木奏',     ['https://haikyo.co.jp/photo/13118-4.jpg'], None, 'kana_nogi0911', '9月11日'),
    ('小田杏树',   ['https://axl-one.com/admin/img/talent/90/1.jpg'], None, 'Anju_oda0130', '1月30日'),
    ('井料爱良',   ['https://thetv.jp/person/2000075486/'], 'https://thetv.jp/person/2000075486/', 'Aira_Iryo', '9月19日'),
    ('折原日菜',   ['https://thetv.jp/person/2000069242/'], 'https://thetv.jp/person/2000069242/', 'Hina_orihara_', '5月8日'),
]

for key, urls, pageurl, handle, birth in JOBS:
    fn = 'va_%s.jpg' % sanitize(key)
    final = os.path.join(OUT_DIR, fn)
    done = False
    for u in urls:
        try:
            img_url = u if not u.endswith('/') else og_image(u)
            if not img_url:
                print(key, ': no og:image at', u)
                continue
            data = fetch(img_url)
            try:
                save_img(data, final)
                sz = os.path.getsize(final) // 1024
                print('%s OK <- %s (%dKB)' % (key, img_url[:90], sz))
                entry = {'img': '/uma_va/' + fn, 'page': pageurl or ('https://x.com/' + handle), 'title': '@' + handle, 'birth': birth}
                manifest[key] = entry
                st[key] = {'ok': True, 'entry': entry}
                done = True
                break
            except ValueError as ex:
                print(key, ': reject', str(ex), img_url[:70])
        except Exception as ex:
            print(key, ': FAIL', str(ex)[:80], '|', u[:80])
    if not done:
        print('%s: STILL MISSING' % key)

json.dump(st, open(STATE, 'w', encoding='utf-8'), ensure_ascii=False)
out = ['// auto-generated by fetch_va_photos_moegirl.py']
out.append('window.VA_PHOTOS = %s;' % json.dumps(manifest, ensure_ascii=False))
open(MANIFEST, 'w', encoding='utf-8').write('\n'.join(out))
missing = [k for k, *_ in JOBS if k not in manifest]
print('DONE total=%d missing=%s' % (len(manifest), missing or 'none'))
