# -*- coding: utf-8 -*-
"""Fetch photos+birthdays for 4 former VAs, merge into va_photos_data.js."""
import urllib.request, urllib.parse, json, re, os, time, io, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
from PIL import Image

ROOT = r'G:\学习\AI'
OUT_DIR = os.path.join(ROOT, 'uma_va')
MANIFEST = os.path.join(ROOT, 'va_photos_data.js')
STATE = r'C:\Users\51673\AppData\Local\Temp\opencode\va_photo_state2.json'
UA = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
DATE_RE = re.compile(r'(19|20)\d{2}年\d{1,2}月\d{1,2}日')

TARGETS = {
    '伊波杏樹': ['伊波杏樹', '伊波杏树'],
    '相坂優歌': ['相坂優歌', '相坂优歌'],
    '今村彩夏': ['今村彩夏'],
    '岭内知美': ['岭内知美', '岭内智美', '嶺内ともみ'],
}

def get_json(url):
    return json.loads(urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=25).read().decode('utf-8'))

def get_bytes(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=40).read()

def get_html(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30).read().decode('utf-8', 'replace')

def api_quote(t):
    return urllib.parse.quote(t.replace(' ', '_'), safe='')

def find_page(cands):
    for nm in cands:
        q = urllib.parse.quote(nm)
        try:
            r = get_json('https://zh.moegirl.org.cn/api.php?action=opensearch&search=%s&limit=5&format=json' % q)
            titles = r[1] if len(r) > 1 else []
        except Exception:
            continue
        for t in titles:
            if nm in t:
                return t
        if titles:
            return titles[0]
    return None

def get_photo(title):
    try:
        r = get_json('https://zh.moegirl.org.cn/api.php?action=query&titles=%s&prop=pageimages&piprop=thumbnail&pithumbsize=560&format=json' % api_quote(title))
    except Exception:
        return None
    for _, pg in r.get('query', {}).get('pages', {}).items():
        th = (pg.get('thumbnail') or {}).get('source')
        if th:
            return th
    return None

def extract_birth(html):
    rows = re.findall(r'<tr[^>]*>((?:(?!</tr>).)*?(?:出生|生年|生日|诞辰)(?:(?!</tr>).)*?)</tr>', html, re.S)
    for row in rows:
        txt = re.sub(r'<[^>]+>', ' ', row)
        txt = re.sub(r'\s+', ' ', txt).strip()
        if '索引' in txt or '查' in txt[:3]:
            continue
        m = DATE_RE.search(txt)
        if m:
            return m.group(0)
    return ''

def sanitize(name):
    s = re.sub(r'[^\w\u4e00-\u9fff\u3040-\u30ff\u3005\u3006\u30fc]+', '_', str(name))
    return s.strip('_') or 'va'

src = open(MANIFEST, encoding='utf-8').read()
manifest = json.loads(re.search(r'window\.VA_PHOTOS\s*=\s*(\{.*\});?\s*$', src, re.S).group(1))
st = json.load(open(STATE, encoding='utf-8')) if os.path.exists(STATE) else {}

for key, cands in TARGETS.items():
    if key in manifest and manifest[key].get('img') and os.path.exists(os.path.join(ROOT, manifest[key]['img'].lstrip('/'))):
        print('SKIP (have)', key)
        continue
    title = find_page(cands)
    time.sleep(0.2)
    print(key, '-> page:', title)
    if not title:
        continue
    ph = get_photo(title)
    time.sleep(0.2)
    birth = ''
    entry = None
    if ph:
        fn = 'va_%s.jpg' % sanitize(key)
        try:
            data = get_bytes(ph)
            tmp = os.path.join(OUT_DIR, '_tmp_' + fn)
            open(tmp, 'wb').write(data)
            img = Image.open(tmp)
            if img.mode in ('RGBA', 'P'):
                img = img.convert('RGB')
            w, h = img.size
            if w > 300:
                img = img.resize((300, int(h * 300 / w)), Image.LANCZOS)
            final = os.path.join(OUT_DIR, fn)
            img.save(final, 'JPEG', quality=75, optimize=True)
            os.remove(tmp)
            sz = os.path.getsize(final) // 1024
            print('  photo saved:', fn, sz, 'KB')
            entry = {'img': '/uma_va/' + fn, 'page': 'https://zh.moegirl.org.cn/' + api_quote(title), 'title': title}
        except Exception as ex:
            print('  DL FAIL', str(ex)[:80])
    else:
        print('  no thumbnail')
    try:
        html = get_html('https://zh.moegirl.org.cn/' + api_quote(title))
        birth = extract_birth(html)
    except Exception:
        pass
    time.sleep(0.2)
    print('  birth:', birth or '(none)')
    if entry is not None:
        entry['birth'] = birth
        manifest[key] = entry
        st[key] = {'ok': True, 'entry': entry}
    elif birth:
        st[key] = {'ok': False, 'birth_try': birth}

json.dump(st, open(STATE, 'w', encoding='utf-8'), ensure_ascii=False)
out = ['// auto-generated by fetch_va_photos_moegirl.py']
out.append('window.VA_PHOTOS = %s;' % json.dumps(manifest, ensure_ascii=False))
open(MANIFEST, 'w', encoding='utf-8').write('\n'.join(out))
print('DONE total=%d' % len(manifest))
